name: Build/release

on: push

jobs:
    build_on_win:
        runs-on: windows-latest
        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@master
          with:
            node-version: 20
        - name: install dependencies
          run: npm install
        - name: build
          run: npm run make
        - name: Zip
          uses: actions/upload-artifact@v4
          with:
              name: result
              path: out/make/*
